language: python
python:
    - "3.6"
before_script:
    - bash install.sh
    - export PATH=$PATH:/home/travis/build/SGBC/capture/canu/Linux-amd64/bin/
install:
    - pip install pipenv
    - pipenv install --dev
script:
    - pipenv run test
after_success:
    - pipenv run codecov
notifications:
    email: false
